version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test

  oracle:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-xe
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=test