spring:
  jpa:
    database: POSTGRESQL
  datasource:
    postgres:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/xa_pg
      username: postgres
      password:
    oracle:
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: system
      password: test